### PR TITLE
feat: add core layer

### PR DESCRIPTION
**Pull request by pcfreak30**

### CODE REVIEW

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by ghost** [comment]
| Project | Status | Plan | + | ~ | - |
|---------|--------|------|---|---|---|
|:x: **core** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12359312367'>failed</a> | <a href=''>Plan</a> | 0 | 0 | 0|

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Pull request merged**
