### PR TITLE
feat: add portal layer

### PR DESCRIPTION
**Pull request by pcfreak30**

### CODE REVIEW

**Comment by pcfreak30** [comment]
digger apply

**Comment by ghost** [comment]
| Project | Status | Apply | + | ~ | - |
|---------|--------|------|---|---|---|
|:white_check_mark: **core** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12365030554'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2547354789'>Apply</a> | 0 | 0 | 0|
|:white_check_mark: **portal** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12365040368'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2547358037'>Apply</a> | 6 | 0 | 0|

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
caddy plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by ghost** [comment]
| Project | Status | Plan | + | ~ | - |
|---------|--------|------|---|---|---|
|:white_check_mark: **portal** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12409419810'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2553123223'>Plan</a> | 3 | 0 | 0|
|:white_check_mark: **core** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12409408789'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2553121375'>Plan</a> | 0 | 0 | 0|

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by ghost** [comment]
| Project | Status | Apply | + | ~ | - |
|---------|--------|------|---|---|---|
|:white_check_mark: **core** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12409906333'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2553185432'>Apply</a> | 0 | 0 | 0|
|:x: **portal** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12409919513'>failed</a> | <a href=''>Apply</a> | 0 | 0 | 0|

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by ghost** [comment]
| Project | Status | Plan | + | ~ | - |
|---------|--------|------|---|---|---|
|:white_check_mark: **core** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12413278051'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2553864214'>Plan</a> | 0 | 0 | 0|
|:x: **portal** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12413298741'>failed</a> | <a href=''>Plan</a> | 0 | 0 | 0|

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
docker apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by ghost** [comment]
| Project | Status | Apply | + | ~ | - |
|---------|--------|------|---|---|---|
|:white_check_mark: **core** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12424210318'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2556120487'>Apply</a> | 0 | 0 | 0|
|:white_check_mark: **portal** |<a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/actions/runs/12424219506'>succeeded</a> | <a href='https://github.com/LumeWeb/testing.pinner.xyz-devops/pull/4#issuecomment-2556121603'>Apply</a> | 1 | 0 | 0|

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
caddy apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger apply

**Comment by pcfreak30** [comment]
digger plan

**Pull request merged**
